# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Auto-generated invoice ID (e.g., INV-2026-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Invoice lifecycle stage', max_length=20)),
                ('invoice_date', models.DateField(help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment deadline')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('on_delivery', 'On Delivery'), ('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('on_return', 'On Return')], default='immediate', help_text='When payment is expected', max_length=20)),
                ('billing_name', models.CharField(help_text="Customer's company name for invoice", max_length=255)),
                ('billing_gstin', models.CharField(help_text="Customer's GSTIN for GST compliance", max_length=15)),
                ('billing_address', models.TextField(help_text="Customer's billing address")),
                ('billing_state', models.CharField(help_text='State for GST calculation (intra-state vs inter-state)', max_length=100)),
                ('vendor_name', models.CharField(help_text="Vendor's company name", max_length=255)),
                ('vendor_gstin', models.CharField(help_text="Vendor's GSTIN", max_length=15)),
                ('vendor_address', models.TextField(help_text="Vendor's business address")),
                ('vendor_state', models.CharField(help_text="Vendor's state (for GST type determination)", max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all invoice lines before tax/discount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied', max_digits=12)),
                ('is_intrastate', models.BooleanField(default=True, help_text='Same state transaction (CGST+SGST) or inter-state (IGST)')),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='Central GST rate % (typically 9% for 18% total GST)', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='State GST rate % (typically 9% for 18% total GST)', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Integrated GST rate % (for inter-state)', max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Central GST amount (intra-state only)', max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='State GST amount (intra-state only)', max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Integrated GST amount (inter-state only)', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax (CGST+SGST or IGST)', max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Late return penalties', max_digits=12)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Equipment damage costs', max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Miscellaneous charges (delivery, packaging, etc.)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final invoice total (subtotal - discount + tax + fees)', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far', max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid', max_digits=12)),
                ('deposit_collected', models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit collected upfront', max_digits=12)),
                ('deposit_refunded', models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit returned after successful return', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or special instructions', null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to customer on invoice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When invoice was sent to customer', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When invoice was fully paid', null=True)),
                ('customer', models.ForeignKey(help_text='Customer being billed', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('rental_order', models.ForeignKey(help_text='Rental order being invoiced', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rentals.rentalorder')),
                ('vendor', models.ForeignKey(help_text='Vendor issuing the invoice', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Line item description (e.g., 'Canon EOS R5 Rental (Jan 15-20, 2026)')", max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantity (units or days)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=12)),
                ('is_taxable', models.BooleanField(default=True, help_text='Should GST be applied to this line')),
                ('hsn_code', models.CharField(blank=True, help_text='HSN code for goods / SAC for services (GST requirement)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Parent invoice document', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='billing.invoice')),
                ('rental_order_line', models.ForeignKey(blank=True, help_text='Source order line (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='rentals.rentalorderline')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'invoice_lines',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='Auto-generated payment ID (e.g., PAY-2026-0001)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cheque', 'Cheque'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('other', 'Other')], help_text='How customer paid', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment confirmation status', max_length=20)),
                ('payment_date', models.DateTimeField(help_text='When payment was made')),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction reference', max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw payment gateway response (for debugging/reconciliation)')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for cheque/transfer payments', max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, help_text='Cheque number if payment method is cheque', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or reference information', null=True)),
                ('is_refund', models.BooleanField(default=False, help_text='Is this a refund transaction?')),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payment was confirmed/failed', null=True)),
                ('customer', models.ForeignKey(help_text='Customer making the payment', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text='Invoice being paid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('original_payment', models.ForeignKey(blank=True, help_text='Original payment being refunded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='invoices_custome_90a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'status'], name='invoices_vendor__3bd587_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='invoices_due_dat_4b5593_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_status'], name='payments_invoice_bab455_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_status'], name='payments_custome_c1db85_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_payment_c27a96_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
    ]
