# Generated by Django 5.1.5 on 2026-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number if payment method is cheque (Encrypted)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction reference (Encrypted)', max_length=255, null=True),
        ),
    ]
