# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(help_text='Auto-generated unique quotation ID (e.g., QT-2026-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current quotation stage', max_length=20)),
                ('valid_until', models.DateField(help_text='Quotation expires after this date (typical: 7-30 days)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line items before tax/discount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='GST calculated (CGST+SGST or IGST)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final quotation amount (subtotal - discount + tax)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or terms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When customer confirmed this quotation', null=True)),
                ('customer', models.ForeignKey(help_text='Customer requesting the rental quote', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateTimeField(help_text='When customer wants to pick up the item')),
                ('rental_end_date', models.DateTimeField(help_text='When customer will return the item')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units to rent', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Rental price per unit for the specified duration', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=12)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Calculated rental duration in days')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Additional hours beyond full days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being quoted', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Specific variant if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='catalog.productvariant')),
                ('quotation', models.ForeignKey(help_text='Parent quotation document', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='rentals.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Line',
                'verbose_name_plural': 'Quotation Lines',
                'db_table': 'quotation_lines',
                'ordering': ['quotation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Auto-generated unique order ID (e.g., RO-2026-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('invoiced', 'Invoiced')], default='draft', help_text='Current order stage in the rental lifecycle', max_length=20)),
                ('delivery_address', models.TextField(help_text='Where items will be delivered/picked up')),
                ('billing_address', models.TextField(help_text='Address for invoice (may differ from delivery)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all order lines', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='GST amount', max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Late return penalties (added if items returned late)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final order total including all fees', max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit collected upfront', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far (partial or full)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or customer requests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When order was confirmed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all items were returned', null=True)),
                ('customer', models.ForeignKey(help_text='Customer placing the rental order', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(blank=True, help_text='Source quotation that was converted to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_order', to='rentals.quotation')),
                ('vendor', models.ForeignKey(help_text='Vendor fulfilling the rental order', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rental_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Order',
                'verbose_name_plural': 'Rental Orders',
                'db_table': 'rental_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_number', models.CharField(help_text='Auto-generated pickup document ID (e.g., PU-2026-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Pickup process stage', max_length=20)),
                ('scheduled_pickup_date', models.DateTimeField(help_text='When customer plans to pick up items')),
                ('actual_pickup_date', models.DateTimeField(blank=True, help_text='When items were actually handed over', null=True)),
                ('items_checked', models.BooleanField(default=False, help_text='Vendor verified all items before handover')),
                ('customer_id_verified', models.BooleanField(default=False, help_text='Customer identity verified')),
                ('pickup_notes', models.TextField(blank=True, help_text='Condition notes, missing accessories, damages observed at pickup', null=True)),
                ('customer_signature', models.TextField(blank=True, help_text='Digital signature data (base64) or acknowledgment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handed_over_by', models.ForeignKey(blank=True, help_text='Vendor staff who processed this pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_processed', to=settings.AUTH_USER_MODEL)),
                ('rental_order', models.OneToOneField(help_text='Associated rental order', on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='rentals.rentalorder')),
            ],
            options={
                'verbose_name': 'Pickup',
                'verbose_name_plural': 'Pickups',
                'db_table': 'pickups',
                'ordering': ['-scheduled_pickup_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateTimeField(help_text='Scheduled pickup date/time')),
                ('rental_end_date', models.DateTimeField(help_text='Scheduled return date/time')),
                ('actual_pickup_date', models.DateTimeField(blank=True, help_text='When customer actually picked up the item', null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, help_text='When customer actually returned the item', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units rented', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Rental price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=12)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Rental duration in days')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Additional hours beyond full days')),
                ('is_late_return', models.BooleanField(default=False, help_text='Item returned after scheduled end date')),
                ('late_days', models.PositiveIntegerField(default=0, help_text='Number of days late (0 if on time)')),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0.0, help_text='Late return penalty amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being rented', on_delete=django.db.models.deletion.CASCADE, related_name='rental_order_lines', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Specific variant being rented', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_order_lines', to='catalog.productvariant')),
                ('rental_order', models.ForeignKey(help_text='Parent rental order', on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='rentals.rentalorder')),
            ],
            options={
                'verbose_name': 'Rental Order Line',
                'verbose_name_plural': 'Rental Order Lines',
                'db_table': 'rental_order_lines',
                'ordering': ['rental_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateTimeField(help_text='Reservation start (blocks inventory from this date)')),
                ('rental_end_date', models.DateTimeField(help_text='Reservation end (inventory released after this date)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units are blocked')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', help_text='Reservation lifecycle stage', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product whose inventory is blocked', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Specific variant being reserved', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant')),
                ('rental_order_line', models.ForeignKey(help_text='Which order line created this reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rentals.rentalorderline')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
                'ordering': ['rental_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(help_text='Auto-generated return document ID (e.g., RT-2026-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partial Return'), ('damaged', 'Returned with Damage')], default='pending', help_text='Return process stage', max_length=20)),
                ('scheduled_return_date', models.DateTimeField(help_text='When customer should return items (from order)')),
                ('actual_return_date', models.DateTimeField(blank=True, help_text='When items were actually returned', null=True)),
                ('all_items_returned', models.BooleanField(default=False, help_text='All rented items accounted for')),
                ('items_damaged', models.BooleanField(default=False, help_text='Any items returned with damage')),
                ('damage_description', models.TextField(blank=True, help_text='Detailed damage assessment (for security deposit deduction)', null=True)),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Repair/replacement cost (deducted from deposit)', max_digits=10)),
                ('is_late_return', models.BooleanField(default=False, help_text='Returned after scheduled date')),
                ('late_days', models.PositiveIntegerField(default=0, help_text='Number of days late')),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0.0, help_text='Late return penalty', max_digits=10)),
                ('return_notes', models.TextField(blank=True, help_text='Inspection notes, customer feedback, issues', null=True)),
                ('customer_signature', models.TextField(blank=True, help_text='Customer acknowledgment of return condition', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, help_text='Vendor staff who processed this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('rental_order', models.OneToOneField(help_text='Associated rental order', on_delete=django.db.models.deletion.CASCADE, related_name='return_doc', to='rentals.rentalorder')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'returns',
                'ordering': ['-scheduled_return_date'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', 'status'], name='quotations_custome_bf8f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations_quotati_298c04_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['customer', 'status'], name='rental_orde_custome_ec257c_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['vendor', 'status'], name='rental_orde_vendor__96529d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['order_number'], name='rental_orde_order_n_44d950_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['product', 'status', 'rental_start_date', 'rental_end_date'], name='reservation_product_29a0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['product_variant', 'status', 'rental_start_date', 'rental_end_date'], name='reservation_product_925c95_idx'),
        ),
    ]
