# Generated by Django 5.1.5 on 2026-01-31 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this quotation was approved', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin or vendor who approved this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this quotation needs approval (for high-value orders)'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this order was approved', null=True),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rental_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this order needs approval (for high-value orders)'),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='Auto-generated unique approval request ID (e.g., APR-2026-0001)', max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('quotation', 'Quotation Approval'), ('order', 'Order Approval')], help_text='Type of approval being requested', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current approval status', max_length=20)),
                ('approval_notes', models.TextField(blank=True, help_text='Reason for approval or rejection', null=True)),
                ('approval_amount', models.DecimalField(decimal_places=2, help_text='Total amount requiring approval', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When approval decision was made', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, help_text='Quotation requiring approval (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='rentals.quotation')),
                ('rental_order', models.ForeignKey(blank=True, help_text='Rental order requiring approval (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='rentals.rentalorder')),
                ('requested_by', models.ForeignKey(help_text='User who triggered the approval request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', 'status'], name='approval_re_request_a2a4f3_idx'), models.Index(fields=['requested_by', 'status'], name='approval_re_request_5440d5_idx'), models.Index(fields=['approved_by', 'status'], name='approval_re_approve_e94aba_idx')],
            },
        ),
    ]
