# Generated by Django 5.1.5 on 2026-01-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalinquiry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_product_925c95_idx',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='rentalorderline',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='product_variant',
        ),
    ]
