# Generated by Django 5.1.5 on 2026-01-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rentalpricing_is_active'),
        ('rentals', '0004_remove_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='rentalorderline',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant being rented', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_order_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant being reserved', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['product_variant', 'status', 'rental_start_date', 'rental_end_date'], name='reservation_product_925c95_idx'),
        ),
    ]
