# Generated by Django 6.0.1 on 2026-01-31 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_quotationline_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='advance_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated advance amount to be paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='advance_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Required advance payment % for this quotation', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='advance_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated advance amount expected', max_digits=12),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='advance_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Required advance payment % for this order', max_digits=5),
        ),
    ]
