# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Used for login and notifications', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='customer', help_text="Determines user's permissions and accessible features", max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact number for order notifications and support', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status for security')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Registered business name for invoicing', max_length=255)),
                ('gstin', models.CharField(help_text='GST Identification Number - mandatory for tax invoices', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN (15 characters)', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('billing_address', models.TextField(help_text='Default address for invoice generation')),
                ('shipping_address', models.TextField(blank=True, help_text='Delivery address for rented equipment (can differ from billing)', null=True)),
                ('state', models.CharField(help_text='State for GST calculation (CGST+SGST vs IGST)', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(help_text='Postal code for delivery logistics', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode', regex='^\\d{6}$')])),
                ('signup_coupon', models.CharField(blank=True, help_text='Coupon code used during registration (for discounts/tracking)', max_length=50, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total number of rental orders placed')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime revenue from this customer', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Links to the User account', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text="Vendor's registered business name", max_length=255)),
                ('gstin', models.CharField(help_text="Vendor's GST number for tax compliance", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN (15 characters)', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('business_address', models.TextField(help_text="Vendor's business location")),
                ('state', models.CharField(help_text='State for GST calculations', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode', regex='^\\d{6}$')])),
                ('bank_account_number', models.CharField(blank=True, help_text='For revenue payouts', max_length=20, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_products', models.PositiveIntegerField(default=0, help_text='Number of products listed by this vendor')),
                ('total_rentals', models.PositiveIntegerField(default=0, help_text='Total rental orders fulfilled')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime earnings from rentals', max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Customer satisfaction score (0-5)', max_digits=3)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required before vendor can list products')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When admin approved this vendor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Links to the Vendor User account', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'db_table': 'vendor_profiles',
            },
        ),
    ]
