# Generated by Django 5.1.5 on 2026-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether TOTP 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for 2FA (encrypted)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for instant payouts (encrypted)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gstin',
            field=models.CharField(help_text='GST Identification Number - mandatory for tax invoices (encrypted)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='For revenue payouts (encrypted)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code for bank transfers (encrypted)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='gstin',
            field=models.CharField(help_text="Vendor's GST number for tax compliance (encrypted)", max_length=255, unique=True),
        ),
    ]
