# Generated by Django 5.1.5 on 2026-01-31 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_totp_enabled_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='When deletion was requested')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of deletion request', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="User's reason for requesting deletion", null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When data deletion was completed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejecting deletion request (e.g., legal hold)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when request was made', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the deletion process', null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Admin who completed the deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting data deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Deletion Request',
                'verbose_name_plural': 'Data Deletion Requests',
                'db_table': 'data_deletion_requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('data_processing', 'Data Processing'), ('marketing', 'Marketing Communications'), ('cookies', 'Cookie Usage'), ('third_party_sharing', 'Third-Party Data Sharing')], help_text='Type of consent given', max_length=50)),
                ('granted', models.BooleanField(default=False, help_text='Whether consent was granted or withdrawn')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When consent was given or withdrawn')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent when consent was given', null=True)),
                ('policy_version', models.CharField(default='1.0', help_text='Version of the policy user consented to', max_length=20)),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='When consent was withdrawn (if applicable)', null=True)),
                ('user', models.ForeignKey(help_text='User who gave consent', on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'db_table': 'user_consents',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='user_consen_user_id_4f2eed_idx'), models.Index(fields=['granted_at'], name='user_consen_granted_4e54e8_idx')],
            },
        ),
    ]
