# Generated by Django 5.1.5 on 2026-01-31 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_datadeletionrequest_userconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for the API key (e.g., 'Mobile App')", max_length=100)),
                ('key_hash', models.CharField(help_text='SHA256 hash of the API key', max_length=64, unique=True)),
                ('prefix', models.CharField(default='sk_', help_text='API key prefix', max_length=10)),
                ('last_four', models.CharField(help_text='Last four characters of the API key for display', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the API key was created')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time the API key was used', null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, help_text='IP address from last API key use', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Total number of times the API key was used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for the API key', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the API key was revoked', null=True)),
                ('user', models.ForeignKey(help_text='Owner of the API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_keys_user_id_55f03a_idx'), models.Index(fields=['key_hash'], name='api_keys_key_has_8f2f29_idx'), models.Index(fields=['last_used_at'], name='api_keys_last_us_fbf652_idx')],
            },
        ),
    ]
