# Generated by Django 5.1.5 on 2026-01-31 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(help_text='Links to the Vendor User account', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
