# Generated by Django 6.0.1 on 2026-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='advance_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Percentage of total to be paid as advance (for 'custom' type)", max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='advance_payment_type',
            field=models.CharField(choices=[('none', 'No Advance Required'), ('half', '50% Advance Required'), ('full', '100% Advance Required'), ('custom', 'Custom Percentage Advance')], default='none', help_text='Standard advance payment policy for this vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_logo',
            field=models.ImageField(blank=True, help_text="Vendor's business logo for documents", null=True, upload_to='vendors/logos/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='Bank branch code (encrypted)', max_length=255, null=True),
        ),
    ]
