# Generated by Django 6.0.1 on 2026-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendorprofile_advance_payment_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Registered business name for invoicing (optional for individuals)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number - mandatory for tax invoices (encrypted, optional for individuals)', max_length=255, null=True, unique=True),
        ),
    ]
