# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email of user (stored for record even if user deleted)', max_length=254)),
                ('user_role', models.CharField(help_text="User's role at time of action (customer/vendor/admin)", max_length=20)),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('state_change', 'State Changed'), ('payment', 'Payment Recorded'), ('login', 'User Login'), ('logout', 'User Logout')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text="Django model that was affected (e.g., 'RentalOrder', 'Invoice')", max_length=100)),
                ('object_id', models.CharField(help_text='ID of the affected record', max_length=50)),
                ('object_repr', models.CharField(help_text="String representation of the object (e.g., 'RO-2026-0001')", max_length=255)),
                ('field_name', models.CharField(blank=True, help_text="Specific field changed (e.g., 'status', 'paid_amount')", max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after change', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device information', max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key for grouping related actions', max_length=40, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text="Additional context-specific data (e.g., {'payment_gateway': 'razorpay', 'transaction_id': 'pay_123'})")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null if system-automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
