# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Attribute name (e.g., 'Brand', 'Color', 'Size')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=100)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('multiselect', 'Multiple Selection'), ('number', 'Number')], default='text', help_text='How this attribute is entered/selected', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Must be specified for product creation')),
                ('is_variant_attribute', models.BooleanField(default=False, help_text="If True, creates product variants (e.g., 'Canon EOS R5 Body' vs 'Canon EOS R5 Kit')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'db_table': 'product_attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Camera Equipment', 'Furniture')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description for SEO and customer guidance', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide category on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Canon EOS R5 Mirrorless Camera')", max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed product description for customer decision-making')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for product listings', max_length=500, null=True)),
                ('image_main', models.ImageField(blank=True, help_text='Primary product image', null=True, upload_to='products/images/')),
                ('is_rentable', models.BooleanField(default=True, help_text='Can this product be rented? (vs purchase-only)')),
                ('is_published', models.BooleanField(default=False, help_text='Visible on website. Vendors can unpublish temporarily.')),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Total physical inventory owned by vendor')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text="Vendor's acquisition cost (for margin calculation)", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Dynamic attributes like Brand, Model, Color (JSON: {'brand': 'Canon', 'model': 'EOS R5'})")),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this product', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Product classification for filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text="Variant identifier (e.g., 'Body Only', '24-70mm Kit', 'Pro Bundle')", max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit for inventory tracking', max_length=100, unique=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Inventory for this specific variant')),
                ('variant_attributes', models.JSONField(default=dict, help_text="Attributes that differentiate this variant (JSON: {'lens': '24-70mm', 'accessories': 'Battery Grip'})")),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price for this variant', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Variant-specific image', null=True, upload_to='products/variants/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this variant available for rental?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Parent product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['product', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='RentalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('custom', 'Custom Duration')], help_text='Rental period unit', max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=1, help_text="Number of units (e.g., 2 for '2 days', 3 for '3 hours')", validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Rental price for this duration', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_discounted', models.BooleanField(default=False, help_text='Promotional pricing active')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount % if promotional pricing is active', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Applies to all variants if set at product level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_prices', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Variant-specific pricing overrides product pricing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_prices', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Rental Pricing',
                'verbose_name_plural': 'Rental Pricing',
                'db_table': 'rental_pricing',
                'ordering': ['product', 'duration_type', 'duration_value'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The actual value (e.g., 'Canon', 'Red', 'Large')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order in dropdown lists')),
                ('is_active', models.BooleanField(default=True, help_text='Available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(help_text='Which attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productattribute')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'db_table': 'attribute_values',
                'ordering': ['attribute', 'display_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'is_published'], name='products_vendor__a5069f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_published'], name='products_categor_326747_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_name')},
        ),
    ]
