# Generated by Django 5.1.5 on 2026-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpricing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable this pricing tier'),
        ),
    ]
