# Generated by Django 6.0.1 on 2026-01-31 06:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('quotation_created', 'Quotation Created'), ('quotation_sent', 'Quotation Sent to Customer'), ('order_confirmed', 'Order Confirmed'), ('pickup_reminder', 'Pickup Reminder'), ('return_reminder', 'Return Reminder'), ('late_return_alert', 'Late Return Alert'), ('invoice_sent', 'Invoice Sent'), ('payment_received', 'Payment Received'), ('welcome_customer', 'Welcome Email (Customer)'), ('welcome_vendor', 'Welcome Email (Vendor)'), ('password_reset', 'Password Reset')], help_text='Email trigger event', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject line (supports variables like {{order_number}})', max_length=255)),
                ('body_html', models.TextField(help_text='HTML email body (supports Django template syntax)')),
                ('body_text', models.TextField(help_text="Plain text fallback for email clients that don't support HTML")),
                ('available_variables', models.JSONField(default=list, help_text="List of variables available for this template (e.g., ['customer_name', 'order_number'])")),
                ('is_active', models.BooleanField(default=True, help_text='Should this template be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Rental ERP', help_text='Company name displayed on invoices and website', max_length=255)),
                ('company_gstin', models.CharField(blank=True, help_text='Master GSTIN (if system is for single company)', max_length=15, null=True)),
                ('company_address', models.TextField(blank=True, help_text='Registered business address', null=True)),
                ('company_state', models.CharField(blank=True, help_text='State for GST calculations', max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, help_text='Customer support phone number', max_length=15, null=True)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for invoices and website header', null=True, upload_to='company/')),
                ('default_cgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='Default CGST rate % (typically 9% for 18% GST)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_sgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='Default SGST rate % (typically 9% for 18% GST)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_igst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Default IGST rate % (typically 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_rental_hours', models.PositiveIntegerField(default=1, help_text='Minimum rental duration in hours')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=90, help_text='How far in advance customers can book (days)')),
                ('quotation_validity_days', models.PositiveIntegerField(default=7, help_text='Default quotation validity period (days)')),
                ('require_deposit', models.BooleanField(default=True, help_text='Require security deposit for rentals')),
                ('default_deposit_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Default deposit % of rental amount', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('invoice_payment_terms_days', models.PositiveIntegerField(default=0, help_text='Default invoice payment terms (0 = immediate)')),
                ('brevo_api_key', models.CharField(blank=True, help_text='Brevo (Sendinblue) SMTP API key for transactional emails', max_length=255, null=True)),
                ('brevo_smtp_server', models.CharField(default='smtp-relay.brevo.com', help_text='Brevo SMTP server address', max_length=255)),
                ('brevo_smtp_port', models.PositiveIntegerField(default=587, help_text='Brevo SMTP port')),
                ('brevo_sender_email', models.EmailField(blank=True, help_text='From email address for notifications', max_length=254, null=True)),
                ('brevo_sender_name', models.CharField(blank=True, help_text='From name for email notifications', max_length=100, null=True)),
                ('appyflow_api_key', models.CharField(blank=True, help_text='AppyFlow API key for GSTIN verification', max_length=255, null=True)),
                ('enable_gstin_verification', models.BooleanField(default=False, help_text='Verify GSTIN via AppyFlow API during signup')),
                ('razorpay_key_id', models.CharField(blank=True, help_text='Razorpay Key ID', max_length=255, null=True)),
                ('razorpay_key_secret', models.CharField(blank=True, help_text='Razorpay Key Secret', max_length=255, null=True)),
                ('enable_razorpay', models.BooleanField(default=False, help_text='Enable Razorpay payment gateway')),
                ('site_title', models.CharField(default='Rental Management System', help_text='Website title (shown in browser tab)', max_length=100)),
                ('site_tagline', models.CharField(blank=True, help_text='Website tagline/slogan', max_length=255, null=True)),
                ('enable_customer_registration', models.BooleanField(default=True, help_text='Allow new customer signups')),
                ('enable_vendor_registration', models.BooleanField(default=False, help_text='Allow new vendor signups (usually admin-only)')),
                ('send_quotation_emails', models.BooleanField(default=True, help_text='Email customer when quotation is created')),
                ('send_order_confirmation_emails', models.BooleanField(default=True, help_text='Email customer when order is confirmed')),
                ('send_pickup_reminders', models.BooleanField(default=True, help_text='Email reminder before pickup date')),
                ('send_return_reminders', models.BooleanField(default=True, help_text='Email reminder before return date')),
                ('return_reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Send return reminder X hours before due date')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
                'db_table': 'system_configuration',
            },
        ),
        migrations.CreateModel(
            name='LateFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., 'Standard Late Fee', 'Premium Equipment Late Fee')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Policy description shown to customers', null=True)),
                ('grace_period_hours', models.PositiveIntegerField(default=2, help_text='Free grace period in hours (e.g., 2 hours late = no charge)')),
                ('penalty_calculation_method', models.CharField(choices=[('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('percentage', 'Percentage of Rental')], default='per_day', help_text='How late fees are calculated', max_length=20)),
                ('penalty_rate_per_day', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed penalty per day (if method = per_day)', max_digits=10)),
                ('penalty_rate_per_hour', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed penalty per hour (if method = per_hour)', max_digits=10)),
                ('penalty_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty as % of original rental amount (if method = percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_penalty_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum late fee amount (prevents excessive charges)', max_digits=10, null=True)),
                ('applies_to_all_products', models.BooleanField(default=True, help_text='Apply this policy to all products')),
                ('is_active', models.BooleanField(default=True, help_text='Is this policy currently in effect')),
                ('effective_from', models.DateField(blank=True, help_text='Policy effective start date', null=True)),
                ('effective_until', models.DateField(blank=True, help_text='Policy expiration date (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_categories', models.ManyToManyField(blank=True, help_text='Apply policy only to these categories (if not all products)', related_name='late_fee_policies', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Late Fee Policy',
                'verbose_name_plural': 'Late Fee Policies',
                'db_table': 'late_fee_policies',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GSTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(help_text='HSN code for this category (GST compliance)', max_length=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, help_text='CGST rate % for this category', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sgst_rate', models.DecimalField(decimal_places=2, help_text='SGST rate % for this category', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('igst_rate', models.DecimalField(decimal_places=2, help_text='IGST rate % for this category', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this configuration active')),
                ('effective_from', models.DateField(help_text='When this GST rate becomes effective')),
                ('effective_until', models.DateField(blank=True, help_text='When this GST rate expires (for rate changes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category this GST rate applies to', on_delete=django.db.models.deletion.CASCADE, related_name='gst_configurations', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'GST Configuration',
                'verbose_name_plural': 'GST Configurations',
                'db_table': 'gst_configurations',
                'ordering': ['category', '-effective_from'],
                'unique_together': {('category', 'effective_from')},
            },
        ),
    ]
