# Generated by Django 5.1.5 on 2026-01-31 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_order_approvals',
            field=models.BooleanField(default=True, help_text='Require approval for high-value orders'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_quotation_approvals',
            field=models.BooleanField(default=True, help_text='Require approval for high-value quotations'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='order_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Orders above this amount require approval', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='quotation_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Quotations above this amount require approval', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
